# Generated by Django 4.0 on 2023-07-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celery_beat', '0002_rename_first_name_author_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='city',
            new_name='hometown',
        ),
        migrations.RemoveField(
            model_name='author',
            name='country',
        ),
    ]
