# Generated by Django 4.0 on 2023-07-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_studentprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='phone_number',
        ),
    ]
